import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Sidebar } from "../components/layouts";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-full flex">
          <Sidebar />
          <main className="bg-gray-100 px-8 py-10 flex-1">{children}</main>
        </div>
      </body>
    </html>
  );
}
